{
 "title": "PC Power",
 "tags": [ "telemetry" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(exporter_information{platform=\"windows\"},host)"
    }
   },
   {
    "name": "sensor",
    "label": "Sensor",
    "query": {
     "query": "label_values(sensor_temperature,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "⚡Power(W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sensor_power{name=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hardware_cpu_power{host=\"$host\", name=~\"^(Package|CPU Package)$\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hardware_gpu_power{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_power{name=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hardware_cpu_power{host=\"$host\", name=~\"^(Package|CPU Package)$\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hardware_gpu_power{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌡️Temperature(℃)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sensor_temperature{name=\"$sensor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hardware_cpu_temperature{host=\"$host\",name=~\"^(CPU Package|Core \\\\(Tctl/Tdie\\\\))$\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hardware_gpu_temperature{host=\"$host\",name=\"GPU Core\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "smart_nvme_value{host=\"$host\",smart_id=\"temperature\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "smart_generic_value{host=\"$host\",smart_id=\"C2\"} % 256",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_temperature{name=\"$sensor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hardware_cpu_temperature{host=\"$host\",name=~\"^(CPU Package|Core \\\\(Tctl/Tdie\\\\))$\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hardware_gpu_temperature{host=\"$host\",name=\"GPU Core\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "smart_nvme_value{host=\"$host\",smart_id=\"temperature\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "smart_generic_value{host=\"$host\",smart_id=\"C2\"} % 256",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⚙️FAN(rpm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "hardware_io_fan{host=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hardware_gpu_fan{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hardware_io_fan{host=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hardware_gpu_fan{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}