{
 "title": "Room",
 "tags": [ "telemetry" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "⚡Power(W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sensor_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "🌡️Temperature(℃)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sensor_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "📶Wi-Fi signal(dB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "wifi_rssi", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "📶BLE signal(dB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "ble_rssi", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "📶Ping(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "ping_result_time", "legendFormat": "__auto" }
   ]
  }
 ]
}