{
 "title": "Sensor",
 "tags": [ "telemetry" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "🌡Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "℃" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_temperature{model=\"rbt\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sensor_temperature{model=\"rbt\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sensor_humidity{model=\"rbt\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "💧Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "％" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_humidity{model=\"rbt\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "😓Discomfort",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_discomfort{model=\"rbt\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔊Noise",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_noise{model=\"rbt\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌪Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_pressure{model=\"rbt\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "💡Light",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_light{model=\"rbt\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🥵Heat",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_heat{model=\"rbt\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌫eCO2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_co2{model=\"rbt\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🏭eTVOC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_tvoc{model=\"rbt\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}