{
 "title": "SMART",
 "tags": [ "telemetry" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "💚Life(%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - smart_nvme_value{smart_id=\"percentage_used\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - label_replace(smart_generic_value{smart_id=\"CA\"}, \"model\", \"$1\", \"model\", \"(.*) USB Device\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌡️Temperature(℃)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "smart_nvme_value{smart_id=\"temperature\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(smart_generic_value{smart_id=\"C2\"}, \"model\", \"$1\", \"model\", \"(.*) USB Device\") % 256",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔌Power cycle(count)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "smart_nvme_value{smart_id=\"power_cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(smart_generic_value{smart_id=\"0C\"}, \"model\", \"$1\", \"model\", \"(.*) USB Device\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🕰️Power on hours(h)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "smart_nvme_value{smart_id=\"power_on_hours\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(smart_generic_value{smart_id=\"09\"}, \"model\", \"$1\", \"model\", \"(.*) USB Device\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📤Total read(GB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "smart_nvme_value{smart_id=\"data_unit_read\"} * 512 * 1000 / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📥Total write(GB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "smart_nvme_value{smart_id=\"data_unit_written\"} * 512 * 1000 / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(smart_generic_value{smart_id=\"F6\"}, \"model\", \"$1\", \"model\", \"(.*) USB Device\") * 512 / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}