{
 "title": "PC Summary",
 "tags": [ "telemetry" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "📈CPU used(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "hardware_cpu_load{name=\"CPU Total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📈Memory used(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "hardware_memory_load{type=\"physical\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📈Disk used(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "100 - system_disk_free{name!~\"_Total|^Harddisk.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📈Network used(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "targets": [
    { "expr": "hardware_network_load", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "🕰Uptime(day)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "targets": [
    { "expr": "system_uptime / 86400", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "📊Handle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    { "expr": "system_handle", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "⚙CPU queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "targets": [
    { "expr": "system_processor_queue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "⚙Memory page",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "targets": [
    { "expr": "system_memory_page", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "⚙Disk queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "system_disk_queue{name!=\"_Total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌐IPv4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "targets": [
    { "expr": "system_tcp_connections_ip4", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "📊Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "targets": [
    { "expr": "system_process", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "📊Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "targets": [
    { "expr": "system_thread", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "📈GPU used(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "hardware_gpu_load{name=\"GPU Core\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌡CPU temperature(℃)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "hardware_cpu_temperature{name=~\"^(CPU Package|Core \\\\(Tctl/Tdie\\\\))$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌡HDD temperature(℃)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "smart_nvme_value{smart_id=\"temperature\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "smart_generic_value{smart_id=\"C2\"} % 256",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "💚SMART life(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100 - smart_nvme_value{smart_id=\"percentage_used\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - smart_generic_value{smart_id=\"CA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🛠Context switch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 16 },
   "targets": [
    { "expr": "system_context_switch", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "🛠Exception dispatch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "targets": [
    { "expr": "system_exception_dispatch", "legendFormat": "__auto" }
   ]
  }
 ]
}